🚨 (shellcheck): Fixed `shellcheck` errors and warnings

diff --git a/bin/sc-colors b/bin/sc-colors
--- a/bin/sc-colors
+++ b/bin/sc-colors
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
 # Script version
-readonly VERSION=0.2.0
-readonly FILENAME=$(basename ${0})
+readonly VERSION="0.2.0"
+FILENAME="$(basename "${0}")"
+readonly FILENAME
 
 read -d "" -r SPRITE <<EOS
 ─▀▀▌───────▐▀▀─
@@ -18,7 +19,7 @@ WIDTH=4
 HEIGHT=2
 
 function print_help() {
-    cat <<USAGE
+	cat <<USAGE
 ${FILENAME}
 Version ${VERSION}
 
@@ -33,112 +34,112 @@ USAGE
 }
 
 function parse_cli_arguments() {
-    while test $# -gt 0; do
-        case ${1} in
-            "--width")
-                test $# -ge 2 || return 1
+	while test $# -gt 0; do
+		case ${1} in
+		"--width")
+			test $# -ge 2 || return 1
 
-                if [[ ${2} -lt 1 ]]; then
-                    echo "Invalid width (w >= 1)"
-                    return 1
-                fi
+			if [[ ${2} -lt 1 ]]; then
+				echo "Invalid width (w >= 1)"
+				return 1
+			fi
 
-                WIDTH=${2}
+			WIDTH=${2}
 
-                shift 2
-                ;;
-            
-            "--height")
-                test $# -ge 2 || return 1
+			shift 2
+			;;
 
-                if [[ ${2} -lt 1 ]]; then
-                    echo "Invalid height (h >= 1)"
-                    return 1
-                fi
+		"--height")
+			test $# -ge 2 || return 1
 
-                HEIGHT=${2}
-                
-                shift 2
-                ;;
+			if [[ ${2} -lt 1 ]]; then
+				echo "Invalid height (h >= 1)"
+				return 1
+			fi
 
-            "--stdin")
-                IFS= read -d '' -n 1 SPRITE   
-                
-                while IFS= read -d '' -n 1 -t 2 c
-                do
-                    SPRITE+=${c}
-                done
+			HEIGHT=${2}
 
-                shift
-                ;;
-            
-            "-s" | "--sprite")
-                test $# -ge 2 || return 1
+			shift 2
+			;;
 
-                SPRITE=${2}
+		"--stdin")
+			IFS= read -rd '' -n 1 SPRITE
 
-                shift 2
-                ;;
+			while IFS= read -rd '' -n 1 -t 2 c; do
+				SPRITE+=${c}
+			done
 
-            "-h" | "--help")
-                print_help
-                exit 0
-                ;;
-            
-            "-v" | "--version")
-                echo ${FILENAME} -- ${VERSION}
-                exit 0
-                ;;
-            
-            "--" )
-                break
-                ;;
-            
-            *)
-                return 1
-            ;;
-        esac
-    done
+			shift
+			;;
+
+		"-s" | "--sprite")
+			test $# -ge 2 || return 1
+
+			SPRITE=${2}
+
+			shift 2
+			;;
+
+		"-h" | "--help")
+			print_help
+			exit 0
+			;;
+
+		"-v" | "--version")
+			echo "${FILENAME} -- ${VERSION}"
+			exit 0
+			;;
+
+		"--")
+			break
+			;;
+
+		*)
+			return 1
+			;;
+		esac
+	done
 }
 
 # ${1} string to draw
 # ${2} how many
 function _print_line() {
-    local -r lines=$(echo "${1}" | wc -l)
-    local line_y=1
+	local -r lines=$(echo "${1}" | wc -l)
+	local line_y=1
 
-    for (( y = 1 ; y <= ${lines} ; y++)); do
-       local line=$(echo "${1}" | head -n ${line_y} | tail -n 1)
+	for ((y = 1; y <= lines; y++)); do
+		local line
+        line=$(echo "${1}" | head -n ${line_y} | tail -n 1)
 
-        for (( n = 0 ; n < ${2} ; n++)); do
-            local color=$((${CURRENT_COLOR} + ${n}))
-            
-            printf "\e[38;5;${color}m${line}"
-        done
+		for ((n = 0; n < ${2}; n++)); do
+			local color=$((CURRENT_COLOR + n))
 
-        echo
+			printf "\e[38;5;%sm%s" "${color}" "${line}"
+		done
 
-        line_y=$((${line_y} + 1))
-    done
+		echo
+
+		line_y=$((line_y + 1))
+	done
 }
 
 # ${1} w
 # ${2} h
 # ${3} string to draw
 function _print() {
-    for (( i = 0 ; i < ${2} ; i++)); do
-        _print_line "${3}" ${1}
-        CURRENT_COLOR=$((${CURRENT_COLOR} + ${1}))
-    done
+	for ((i = 0; i < ${2}; i++)); do
+		_print_line "${3}" "${1}"
+		CURRENT_COLOR=$((CURRENT_COLOR + ${1}))
+	done
 
-    # Reset terminal color
-    tput sgr0
+	# Reset terminal color
+	tput sgr0
 }
 
 function main() {
-    parse_cli_arguments ${@} || exit 1
+	parse_cli_arguments "${@}" || exit 1
 
-    _print ${WIDTH} ${HEIGHT} "${SPRITE}"
+	_print "${WIDTH}" "${HEIGHT}" "${SPRITE}"
 }
 
-main ${@}
+main "${@}"
diff --git a/bin/sc-install_terraform b/bin/sc-install_terraform
--- a/bin/sc-install_terraform
+++ b/bin/sc-install_terraform
@@ -16,37 +16,28 @@ readonly OUTPUT="terraform_${VERSION}_${ARCH}.zip"
 cd /tmp
 
 # Download checksum and checksum signature
-wget \
-    ${CHECKSUM_URL} \
-    ${CHECKSUM_URL}.sig
+wget "${CHECKSUM_URL}" "${CHECKSUM_URL}.sig"
 
 # Import Hashicorp public key
 curl -s https://www.hashicorp.com/.well-known/pgp-key.txt | gpg --import -
 
 # Verify signature file integrity
-gpg --verify ${CHECKSUM_FILE}.sig ${CHECKSUM_FILE}
-
-if [[ $? -ne 0 ]]; then
-    echo "An error occured while verifying gpg signature"
-    exit 1
+if ! gpg --verify "${CHECKSUM_FILE}.sig" "${CHECKSUM_FILE}"; then
+	echo "An error occured while verifying gpg signature"
+	exit 1
 fi
 
 wget \
-    -O ${OUTPUT} \
-    "https://releases.hashicorp.com/terraform/${VERSION}/${OUTPUT}"
+	-O "${OUTPUT}" \
+	"https://releases.hashicorp.com/terraform/${VERSION}/${OUTPUT}"
 
 # Verify checksum
-sha256sum \
-    -c \
-    --ignore-missing \
-    ${CHECKSUM_FILE}
-
-if [[ $? -ne 0 ]]; then
-    echo "An error occured while verifying checksum"
-    exit 1
+if ! sha256sum -c --ignore-missing "${CHECKSUM_FILE}"; then
+	echo "An error occured while verifying checksum"
+	exit 1
 fi
 
 # Uncompress
-unzip ${OUTPUT}
+unzip "${OUTPUT}"
 mv terraform /usr/bin
-rm -f ${OUTPUT}
+rm -f "${OUTPUT}"
diff --git a/bin/sc-install_tor b/bin/sc-install_tor
--- a/bin/sc-install_tor
+++ b/bin/sc-install_tor
@@ -4,41 +4,38 @@ set -e
 
 readonly VERSION=${1:-"12.0.2"}
 
-readonly DIRNAME=tor-browser
-readonly TARGET=/opt/${DIRNAME}
+readonly DIRNAME="tor-browser"
+readonly TARGET="/opt/${DIRNAME}"
 readonly URL="https://www.torproject.org/dist/torbrowser/${VERSION}/tor-browser-linux64-${VERSION}_ALL.tar.xz"
 
 cd /tmp
 
 # Download
-wget \
-    ${URL} \
-    ${URL}.asc
+wget "${URL}" "${URL}.asc"
 
 # Verify PGP ssignature
 curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf | gpg --import -
 
 gpg \
-    --output ./tor.keyring \
-    --export 0xEF6E286DDA85EA2A4BA7DE684E2C6E8793298290
-gpgv \
-    --keyring ./tor.keyring \
-    tor-browser-linux64-${VERSION}_ALL.tar.xz.asc \
-    tor-browser-linux64-${VERSION}_ALL.tar.xz
+	--output ./tor.keyring \
+	--export 0xEF6E286DDA85EA2A4BA7DE684E2C6E8793298290
 
-if [[ $? -ne 0 ]]; then
-    echo "An error occured while verifying"
-    exit 1
+if ! gpgv \
+	--keyring "./tor.keyring" \
+	"tor-browser-linux64-${VERSION}_ALL.tar.xz.asc" \
+	"tor-browser-linux64-${VERSION}_ALL.tar.xz"; then
+	echo "An error occured while verifying"
+	exit 1
 fi
 
 # Extract
-tar -xvf tor-browser-linux64-${VERSION}_ALL.tar.xz
+tar -xvf "tor-browser-linux64-${VERSION}_ALL.tar.xz"
 
 # Install
-mv ${DIRNAME} ${TARGET}
-cd ${TARGET}
+mv "${DIRNAME}" "${TARGET}"
+cd "${TARGET}"
 ./start-tor-browser.desktop --register-app
 
-ln -sf ${TARGET}/Browser/start-tor-browser /usr/bin/tor-browser
+ln -sf "${TARGET}/Browser/start-tor-browser" "/usr/bin/tor-browser"
 
 update-desktop-database ~/.local/share/applications/
diff --git a/bin/sc-is_live b/bin/sc-is_live
--- a/bin/sc-is_live
+++ b/bin/sc-is_live
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
 # Script version
-readonly VERSION=0.2.0
+readonly VERSION="0.2.0"
 
-readonly FILENAME=$(basename ${0})
+FILENAME="$(basename "${0}")"
+readonly FILENAME
 
 # Constants
 readonly API_URL="https://decapi.me/twitch/uptime"
@@ -20,7 +21,7 @@ DISPLAY_NAME=""
 NOTIFICATION="false"
 
 function print_help() {
-    cat <<USAGE
+	cat <<USAGE
 ${FILENAME}
 Version ${VERSION}
 
@@ -34,155 +35,149 @@ USAGE
 }
 
 function parse_cli_arguments() {
-    while test $# -gt 0; do
-        case ${1} in
-            "-c" | "--channel")
-                test $# -ge 2 || return 1
+	while test $# -gt 0; do
+		case ${1} in
+		"-c" | "--channel")
+			test $# -ge 2 || return 1
 
-                if [[ ${#2} -le 1 ]]; then
-                    echo "Invalid channel name length (c >= 2)"
-                    return 1
-                fi
+			if [[ ${#2} -le 1 ]]; then
+				echo "Invalid channel name length (c >= 2)"
+				return 1
+			fi
 
-                CHANNEL=${2}
-                [[ -z ${DISPLAY_NAME} ]] && DISPLAY_NAME=${CHANNEL}
+			CHANNEL=${2}
+			[[ -z ${DISPLAY_NAME} ]] && DISPLAY_NAME=${CHANNEL}
 
-                shift 2
-                ;;
-            
-            "-d" | "--display")
-                test $# -ge 2 || return 1
+			shift 2
+			;;
 
-                DISPLAY_NAME=${2}
+		"-d" | "--display")
+			test $# -ge 2 || return 1
 
-                shift 2
-                ;;
+			DISPLAY_NAME=${2}
 
-            "-n" | "--notification")
-                NOTIFICATION="true"
+			shift 2
+			;;
 
-                if [[ ! -f ${CACHE_FILE} ]]; then
-                    mkdir -p ${CACHE_PREFIX}
-                    echo "{}" > ${CACHE_FILE}
-                fi
+		"-n" | "--notification")
+			NOTIFICATION="true"
 
-                shift
-                ;;
+			if [[ ! -f ${CACHE_FILE} ]]; then
+				mkdir -p "${CACHE_PREFIX}"
+				echo "{}" >"${CACHE_FILE}"
+			fi
 
-            "-h" | "--help")
-                print_help
-                exit 0
-                ;;
-            
-            "-v" | "--version")
-                echo ${FILENAME} -- ${VERSION}
-                exit 0
-                ;;
-            
-            "--" )
-                break
-                ;;
-            
-            *)
-                return 1
-            ;;
-        esac    
-    done
+			shift
+			;;
+
+		"-h" | "--help")
+			print_help
+			exit 0
+			;;
+
+		"-v" | "--version")
+			echo "${FILENAME} -- ${VERSION}"
+			exit 0
+			;;
+
+		"--")
+			break
+			;;
+
+		*)
+			return 1
+			;;
+		esac
+	done
 }
 
 # i3blocks button event support
 function handle_button() {
-    case ${BLOCK_BUTTON} in
-        1) xdg-open "https://twitch.tv/${CHANNEL}" &> /dev/null &;;
-        3) notify-send "👀 Streamer status module" "\- Left click to open the browser
+	case ${BLOCK_BUTTON} in
+	1) xdg-open "https://twitch.tv/${CHANNEL}" &>/dev/null & ;;
+	3) notify-send "👀 Streamer status module" "\- Left click to open the browser
 ${OFFLINE_EMOJI}: Streamer is offline
 ${ONLINE_EMOJI}: Streamer is online
 ${UNKNOWN_EMOJI}: Unknown satus
 
 ✉️ Send a notification when the streamer is online" ;;
-    esac
+	esac
 }
 
 # ${1} -> current streamer emoji aka status
 function _resolve_emoji() {
-    case ${1} in
-        ${ONLINE_EMOJI}) echo "true" ;;
-        ${OFFLINE_EMOJI}) echo "false" ;;   
-        *) echo "unknown" ;;
-    esac
+	case ${1} in
+	"${ONLINE_EMOJI}") echo "true" ;;
+	"${OFFLINE_EMOJI}") echo "false" ;;
+	*) echo "unknown" ;;
+	esac
 }
 
 # ${1} -> Twitch channel name
 # ${2} -> ${ONLINE_EMOJI} | ${OFFLINE_EMOJI} | ${UNKNOWN_EMOJI}
 function cache_channel() {
-    local -r exist=$(cat "${CACHE_FILE}" | \
-        jq "has(\"${1}\")"
-    )
-    local -r state=$(_resolve_emoji "${2}")
-    local -r udpated_obj=$(cat "${CACHE_FILE}" | \
-        jq ".${1} = ${state}"
-    )
+	local -r exist=$(jq "has(\"${1}\")" <"${CACHE_FILE}")
+	local -r state=$(_resolve_emoji "${2}")
+	local -r udpated_obj=$(jq ".${1} = ${state}" <"${CACHE_FILE}")
 
-    [[ "${state}" == "unknown" ]] && return 1
+	[[ "${state}" == "unknown" ]] && return 1
 
-    if [[ "${exist}" == "false" ]]; then
-        echo "${udpated_obj}" > ${CACHE_FILE}
+	if [[ "${exist}" == "false" ]]; then
+		echo "${udpated_obj}" >"${CACHE_FILE}"
 
-        [[ "${state}" == "true" ]] && return 0
-    fi
+		[[ "${state}" == "true" ]] && return 0
+	fi
 
-    local -r value=$(cat "${CACHE_FILE}" \
-        | jq ".${1}"
-    )
+	local -r value=$(jq ".${1}" <"${CACHE_FILE}")
 
-    echo "${udpated_obj}" > ${CACHE_FILE}
-    
-    if [[
-        "${value}" == "false" && \
-        "${state}" == "true"
-    ]]; then
-        return 0
-    fi
+	echo "${udpated_obj}" >"${CACHE_FILE}"
 
-    return 1
+	if [[ 
+		"${value}" == "false" &&
+		"${state}" == "true" ]] \
+		; then
+		return 0
+	fi
+
+	return 1
 }
 
 # ${1} -> Twitch channel name
 # ${2} -> ${ONLINE_EMOJI} | ${OFFLINE_EMOJI} | ${UNKNOWN_EMOJI}
 function send_notification() {
-    cache_channel $@ || return
+	cache_channel "${@}" || return
 
-    notify-send \
-        -u critical \
-        "👀 ${DISPLAY_NAME} is streaming !"
+	notify-send \
+		-u critical \
+		"👀 ${DISPLAY_NAME} is streaming !"
 }
 
 function print_status() {
-    local -r res=$(curl --silent ${API_URL}/${CHANNEL})
-    local emoji=""
+	local -r res=$(curl --silent "${API_URL}/${CHANNEL}")
+	local emoji=""
 
-    if [[ ${res} =~ "offline" ]]; then
-        emoji=${OFFLINE_EMOJI}
-    elif [[ ${res} =~ "seconds" ]]; then
-        emoji=${ONLINE_EMOJI}
-    else
-        emoji=${UNKNOWN_EMOJI}
-    fi
-    
-    if [[ "${NOTIFICATION}" == "true" ]]; then
-        send_notification ${CHANNEL} ${emoji}
-    fi
+	if [[ ${res} =~ "offline" ]]; then
+		emoji=${OFFLINE_EMOJI}
+	elif [[ ${res} =~ "seconds" ]]; then
+		emoji=${ONLINE_EMOJI}
+	else
+		emoji=${UNKNOWN_EMOJI}
+	fi
 
-    echo "${emoji}${DISPLAY_NAME}"
+	if [[ "${NOTIFICATION}" == "true" ]]; then
+		send_notification "${CHANNEL}" "${emoji}"
+	fi
+
+	echo "${emoji}${DISPLAY_NAME}"
 }
 
 function main() {
-    parse_cli_arguments $@ || exit 1
+	parse_cli_arguments "${@}" || exit 1
 
-    handle_button
+	handle_button
 
-    [[ -z ${CHANNEL} ]] && exit 1
-    print_status
+	[[ -z ${CHANNEL} ]] && exit 1
+	print_status
 }
 
-main $@
+main "${@}"
diff --git a/bin/sc-timer b/bin/sc-timer
--- a/bin/sc-timer
+++ b/bin/sc-timer
@@ -2,14 +2,17 @@
 
 set -e
 
-readonly RESOLVED_DIR=$(dirname $(realpath ${0}))
+RESOLVED_DIR="$(dirname "$(realpath "${0}")")"
+readonly RESOLVED_DIR
 
+# shellcheck source=/dev/null
 source "${RESOLVED_DIR}/../lib/sc-utils"
 
 # Script version
-readonly VERSION=0.2.0
+readonly VERSION="0.2.0"
 
-readonly FILENAME=$(basename ${0})
+FILENAME="$(basename "${0}")"
+readonly FILENAME
 
 # Default vars
 HOUR="00"
@@ -18,7 +21,7 @@ SECOND="00"
 TIMER_STYLE="simple"
 
 function print_help() {
-    cat <<USAGE
+	cat <<USAGE
 ${FILENAME}
 Version ${VERSION}
 
@@ -33,104 +36,104 @@ USAGE
 }
 
 function parse_cli_arguments() {
-    while test $# -gt 0; do
-        case ${1} in
-            "--hours")
-                test $# -ge 2 || return 1
+	while test $# -gt 0; do
+		case ${1} in
+		"--hours")
+			test $# -ge 2 || return 1
 
-                if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
-                    echo "Invalid hour (0 <= H <= 24)"
-                    return 1
-                fi
+			if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
+				echo "Invalid hour (0 <= H <= 24)"
+				return 1
+			fi
 
-                HOUR=${2}
+			HOUR=${2}
 
-                shift 2
-                ;;
+			shift 2
+			;;
 
-            "--minutes")
-                test $# -ge 2 || return 1
+		"--minutes")
+			test $# -ge 2 || return 1
 
-                if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
-                    echo "Invalid minute (0 <= M <= 60)"
-                    return 1
-                fi
+			if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
+				echo "Invalid minute (0 <= M <= 60)"
+				return 1
+			fi
 
-                MINUTE=${2}
+			MINUTE=${2}
 
-                shift 2
-                ;;
+			shift 2
+			;;
 
-            "--seconds")
-                test $# -ge 2 || return 1
+		"--seconds")
+			test $# -ge 2 || return 1
 
-                if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
-                    echo "Invalid minute (0 <= S <= 60)"
-                    return 1
-                fi
+			if [[ ${2} -lt 0 || ${2} -gt 24 ]]; then
+				echo "Invalid minute (0 <= S <= 60)"
+				return 1
+			fi
 
-                SECOND=${2}
+			SECOND=${2}
 
-                shift 2
-                ;;
-            
-            "--timer-style")
-                test $# -ge 2 || return 1
+			shift 2
+			;;
 
-                TIMER_STYLE=${2}
+		"--timer-style")
+			test $# -ge 2 || return 1
 
-                shift 2
-                ;;
+			TIMER_STYLE=${2}
 
-            "-h" | "--help")
-                print_help
-                exit 0
-                ;;
-            
-            "-v" | "--version")
-                echo ${FILENAME} -- ${VERSION}
-                exit 0
-                ;;
-            
-            "--" )
-                break
-                ;;
-            
-            *)
-                return 1
-            ;;
-        esac    
-    done
+			shift 2
+			;;
+
+		"-h" | "--help")
+			print_help
+			exit 0
+			;;
+
+		"-v" | "--version")
+			echo "${FILENAME} -- ${VERSION}"
+			exit 0
+			;;
+
+		"--")
+			break
+			;;
+
+		*)
+			return 1
+			;;
+		esac
+	done
 }
 
 function _timer() {
-    local -r notification_id=$(notify-send "⏳ Clock starting" -p)
-    local timer_format="${HOUR}:${MINUTE}:${SECOND}"
+	local -r notification_id=$(notify-send "⏳ Clock starting" -p)
+	local timer_format="${HOUR}:${MINUTE}:${SECOND}"
 
-    # Default timer is 10 seconds
-    if [[ ${timer_format} == "00:00:00" ]]; then
-        SECOND=10
-        timer_format="${HOUR}:${MINUTE}:${SECOND}"
-    fi
+	# Default timer is 10 seconds
+	if [[ ${timer_format} == "00:00:00" ]]; then
+		SECOND=10
+		timer_format="${HOUR}:${MINUTE}:${SECOND}"
+	fi
 
-    local -r seconds=$(echo "${timer_format}" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
+	local -r seconds=$(echo "${timer_format}" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
 
-    timer \
-        $((${seconds} * 1000)) \
-        ${notification_id} \
-        "normal" \
-        "⏳ ${timer_format}" \
-        "${TIMER_STYLE}"
-    
-    notify-send \
-        -u "critical" \
-        "🏆 Finish !"
+	timer \
+		$((seconds * 1000)) \
+		"${notification_id}" \
+		"normal" \
+		"⏳ ${timer_format}" \
+		"${TIMER_STYLE}"
+
+	notify-send \
+		-u "critical" \
+		"🏆 Finish !"
 }
 
 function main() {
-    parse_cli_arguments ${@} || exit 1
+	parse_cli_arguments "${@}" || exit 1
 
-    _timer
+	_timer
 }
 
-main ${@}
+main "${@}"
diff --git a/bin/sc-wall b/bin/sc-wall
--- a/bin/sc-wall
+++ b/bin/sc-wall
@@ -4,21 +4,29 @@ set -e
 
 # This script is a supposed better version that this old old one https://github.com/theobori/wall.sh/blob/main/wall.sh
 
-readonly RESOLVED_DIR=$(dirname $(realpath ${0}))
+RESOLVED_DIR="$(dirname "$(realpath "${0}")")"
+readonly RESOLVED_DIR
 
+# shellcheck source=/dev/null
 source "${RESOLVED_DIR}/../lib/sc-curses"
+# shellcheck source=/dev/null
 source "${RESOLVED_DIR}/../lib/sc-utils"
 
 # Script version
-readonly VERSION=0.2.0
+readonly VERSION="0.2.0"
 
-readonly FILENAME=$(basename ${0})
+FILENAME="$(basename "${0}")"
+readonly FILENAME
 
 # Terminal global infos
-readonly COLORS=$(tput colors)
-readonly MAX_W=$(tput cols)
-readonly MAX_H=$(tput lines)
-readonly MAX_BLOCKS=$((${MAX_H} * ${MAX_W}))
+COLORS=$(tput colors)
+readonly COLORS
+MAX_W=$(tput cols)
+readonly MAX_W
+MAX_H=$(tput lines)
+readonly MAX_H
+MAX_BLOCKS=$((MAX_H * MAX_W))
+readonly MAX_BLOCKS
 
 BLOCK="\xe2\x96\x88"
 
@@ -29,7 +37,7 @@ INTERVAL=0.01
 RAINBOW=0
 
 function print_help() {
-    cat <<EOF
+	cat <<EOF
 ${FILENAME}
 Version ${VERSION}
 
@@ -45,115 +53,118 @@ EOF
 }
 
 function parse_cli_arguments() {
-    while test $# -gt 0; do
-        case ${1} in
-            "-c" | "--color")
-                if [[ ${2} -lt 0 || ${2} -gt ${COLORS} ]]; then
-                    echo "Invalid color (0 <= c <= 256)"
-                    return 1
-                fi
+	while test $# -gt 0; do
+		case ${1} in
+		"-c" | "--color")
+			if [[ ${2} -lt 0 || ${2} -gt ${COLORS} ]]; then
+				echo "Invalid color (0 <= c <= 256)"
+				return 1
+			fi
 
-                COLOR=${2}
+			COLOR=${2}
 
-                shift 2
-                ;;
+			shift 2
+			;;
 
-            "-s" | "--size")
-                if [[ ${2} -lt 1 || ${2} -gt ${MAX_W} ]]; then
-                    echo "Invalid block size (1 <= b <= ${MAX_W})"
-                    return 1
-                fi
+		"-s" | "--size")
+			if [[ ${2} -lt 1 || ${2} -gt ${MAX_W} ]]; then
+				echo "Invalid block size (1 <= b <= ${MAX_W})"
+				return 1
+			fi
 
-                BLOCK_SIZE=${2}
+			BLOCK_SIZE=${2}
 
-                shift 2
-                ;;
-            
-            "-b" | "--block")
-                if [[ ${#2} -ne 1 ]]; then
-                    echo "Invalid block symbol length (must be 1)"
-                    return 1
-                fi
+			shift 2
+			;;
 
-                BLOCK=${2}
-        
-                shift 2
-                ;;
+		"-b" | "--block")
+			if [[ ${#2} -ne 1 ]]; then
+				echo "Invalid block symbol length (must be 1)"
+				return 1
+			fi
 
-            "-i" | "--interval")
-                INTERVAL=${2}
-        
-                shift 2
-                ;;
+			BLOCK=${2}
 
-            "-r" | "--rainbow")
-                RAINBOW=1
+			shift 2
+			;;
 
-                shift
-                ;;
+		"-i" | "--interval")
+			INTERVAL=${2}
 
-            "-h" | "--help")
-                print_help
-                exit 0
-                ;;
-            
-            "-v" | "--version")
-                echo ${FILENAME} -- ${VERSION}
-                exit 0
-                ;;
-            
-            "--" )
-                break
-                ;;
-            
-            *)
-                return 1
-            ;;
-        esac
-    done
+			shift 2
+			;;
+
+		"-r" | "--rainbow")
+			RAINBOW=1
+
+			shift
+			;;
+
+		"-h" | "--help")
+			print_help
+			exit 0
+			;;
+
+		"-v" | "--version")
+			echo "${FILENAME} -- ${VERSION}"
+			exit 0
+			;;
+
+		"--")
+			break
+			;;
+
+		*)
+			return 1
+			;;
+		esac
+	done
 }
 
 function build_wall() {
-    local x=${1}
-    local y=${2}
-    local -r max=$(expr ${MAX_BLOCKS} / ${BLOCK_SIZE})
+	local x=${1}
+	local y=${2}
+	local -r max=$((MAX_BLOCKS / BLOCK_SIZE))
 
-    for (( i = 0; i < ${max} ; i++ )); do
-        if [[ $(expr ${x} + ${BLOCK_SIZE}) -gt ${MAX_W} ]]; then
-            x=0
-            y=$(expr ${y} + 1)
-            echo
-        fi
+	for ((i = 0; i < max; i++)); do
+		if [[ $((x + BLOCK_SIZE)) -gt MAX_W ]]; then
+			x=0
+			y=$((y + 1))
+			echo
+		fi
 
-        if [[ ${RAINBOW} -eq 1 ]]; then
-            COLOR=$((RANDOM % ${COLORS}))
-        fi
+		if [[ ${RAINBOW} -eq 1 ]]; then
+			COLOR=$((RANDOM % COLORS))
+		fi
 
-        printf "$(tput cup ${y} ${x})\e[38;5;${COLOR}m${BLOCK}"
-        sleep ${INTERVAL}
+        tput cup "${y}" "${x}"
 
-        x=$(expr ${x} + ${BLOCK_SIZE})
-    done
+	    # shellcheck disable=SC2059
+		printf "\e[38;5;${COLOR}m${BLOCK}"
+		sleep "${INTERVAL}"
+
+		x=$((x + BLOCK_SIZE))
+	done
 }
 
 function main() {
-    parse_cli_arguments ${@} || exit 1
+	parse_cli_arguments "${@}" || exit 1
 
-    BLOCK=$(repeat_string ${BLOCK} ${BLOCK_SIZE})
-    BLOCK_ERASER=$(repeat_string "\x20" ${BLOCK_SIZE})
-    local -r tmp=${BLOCK}
+	BLOCK=$(repeat_string "${BLOCK}" "${BLOCK_SIZE}")
+	BLOCK_ERASER=$(repeat_string "\x20" "${BLOCK_SIZE}")
+	local -r tmp="${BLOCK}"
 
-    curses_init
-    
-    while :; do
-        build_wall 0 ${MAX_H}
+	curses_init
 
-        BLOCK=${BLOCK_ERASER}
-        build_wall 0 0
-        BLOCK=${tmp}
-    done
-    
-    curses_reset
+	while :; do
+		build_wall 0 "${MAX_H}"
+
+		BLOCK="${BLOCK_ERASER}"
+		build_wall 0 0
+		BLOCK="${tmp}"
+	done
+
+	curses_reset
 }
 
-main ${@}
+main "${@}"
